// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using Token.Infra.Data;

namespace Token.Infra.Data.Migrations
{
    [DbContext(typeof(TokenContext))]
    [Migration("20190804034349_TokenDB-V4")]
    partial class TokenDBV4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Token.Domain.Entity.TokenEntity", b =>
                {
                    b.Property<DateTime>("Date");

                    b.Property<int>("CVV");

                    b.Property<string>("CardNumber")
                        .IsRequired();

                    b.HasKey("Date");

                    b.ToTable("Token");
                });
#pragma warning restore 612, 618
        }
    }
}
